### PR TITLE
Ember cli update

### PR DESCRIPTION
**Pull request by JonathanPrince**
Update using ember-cli-update to remove deprecation warnings.
Update Mocha to latest version to resolve security vulnerabilities in dependencies.

### CODE REVIEW

**Comment by cibernox** [comment]
LGTM

**Comment by JonathanPrince** [comment]
Hi @cibernox thank you for the quick merge, do you have access and time to publish the update to NPM?

**Comment by cibernox** [comment]
I don't think I do, but I'll check when I'm back on my laptop

**Comment by nikz** [comment]
@JonathanPrince @cibernox thanks for the changes, sorry for the slowness - I've now published everything up :)

**Pull request merged**
