### PR TITLE
updated raygun js and ember cli to current version

### PR DESCRIPTION
**Pull request by aklkv**

### CODE REVIEW

**Comment by nikz** [comment]
@aklkv thanks for the PR! 

Just curious as to why you moved raygun4js from `dependencies` to `devDependencies`? We definitely still want that included in production builds :smile: But I might be missing something?

**Comment by aklkv** [comment]
@nikz oh sorry my bad, I can create new PR

**Comment by nikz** [comment]
Awesome, thanks! Merged :)

**Comment by aklkv** [comment]
could you please push new version to npm

**Comment by nikz** [comment]
@aklkv 1.0.0 published now!

**Pull request merged**
