### PR TITLE
allow passing in raygun options

### PR DESCRIPTION
**Pull request by jakesjews**
Allow passing in options to forward to raygun's initialization.

### CODE REVIEW

**Comment by nikz** [comment]
@jakesjews hi! Thanks, this looks awesome - would you mind adding a quick sanity test?

**Comment by jakesjews** [comment]
No problem

**Comment by nikz** [comment]
Great, ping me if you have any issues!

**Comment by jakesjews** [comment]
@nikz I added a test which passes locally but it looks like one of the four ember try scenarios is failing. I'm not quite sure how to go about debugging it.

**Comment by jakesjews** [comment]
I wasn't able to run the tests with the older packages anymore so I upgraded the project to Ember-CLI 2.7

**Comment by jakesjews** [comment]
@nikz Is there anything else I need to do for this PR?

**Comment by nikz** [comment]
@jakesjews sorry, looks like it's out of date again :( Can you rebase/update to the latest master?

**Comment by jakesjews** [comment]
@nikz no problem

**Comment by jakesjews** [comment]
@nikz I'm all merged up but its pretty tough to rebase since I've merged with upstream a few different times over the past few months. Can we merge it with the commits or would you like me to make a new PR?

**Comment by nikz** [comment]
@jakesjews no problems :) Thanks!

**Comment by jakesjews** [comment]
awesome thanks a bunch!

**Pull request merged**
