### PR TITLE
rg4js v2

### PR DESCRIPTION
**Pull request by typeoneerror**
This is an incomplete PR for replacing the Raygun (v1) lib with the rg4js (v2) API. 

This needs work and tests, but starting a conversation.

### CODE REVIEW

**Comment by nikz** [comment]
@typeoneerror yeah, I've noticed that issue too - let me have a look today and get back to you.

**Comment by typeoneerror** [comment]
@nikz catching up on this. do you have a roadmap for when the error tracking in the v2 api will be asynchronous. happy to wrap this PR up with new implementation when it's ready to rock.

**Comment by nikz** [comment]
@typeoneerror I don't I'm afraid - I guess that would be a question for @CmdrKeen and the Raygun team?

**Comment by dwnz** [comment]
The rg4js setup currently requires the [snippet](https://github.com/MindscapeHQ/raygun4js#getting-started) to work properly. ember-cli-raygun is using v2 of Raygun4JS, it just gets setup using the "V1 style" setup. We have chatted about getting the rg4js proxy stuff running, but don't have any concrete plans. 

Hope this clears things up! Happy to answer any other questions

**Comment by nikz** [comment]
@dwnz does that mean you like us to close this one up?

**Pull request closed without merging**
